### ISSUE TITLE
weighted_pca function - help with variables

### ISSUE THREAD

**Issue by mhwadsworth91** [immunogenomics/singlecellmethods#2]
Hello Ilya et al,

I hope you're well. Thank you for making this package publicly available!

My colleagues and I would like to implement your weighted pca function (weighted_pca), however, we're having difficulty determining what the 'weights' input parameter should be (i.e., can this variable be calculated with a separate function?). Also, is 'X' a harmony object or is the function compatible with SCE/seurat objects?

I tried to find a solution in the Korsunsky 2021 pre-print, however, I was unfortunately unsuccessful (I could have definitely missed this, so I appreciate your patience with resolving this issue). 

For convenience, the code is copied below:

weighted_pca <- function(X, weights, genes_use=NULL, npc=20, do_corr=TRUE, scale_thresh=10) {
    if (!identical(length(weights), ncol(X))) {
        stop('Columns in X must match length of weights')
    }  
    '#' y <- factor(y)
     '#' weights <- as.numeric((1 / prop.table(table(y)))[y]) / nlevels(y)
    if (any(is.na(weights))) {
        idx_keep <- which(is.na(weights))
     '#' y <- y[idx_keep]
        weights <- weights[idx_keep]
        X <- X[, idx_keep]
    }
    if (is.null(genes_use)) {
        genes_use <- row.names(X)
    } else if (length(genes_use) < nrow(X)) {
        if (any(!genes_use %in% row.names(X))) {
            stop('genes_use not in rownames of X')
        }
        X <- X[genes_use, ]
    }
    '##' weighted z-scores
    '#' mu <- X %>% apply(1, function(x) {SDMTools:::wt.mean(x, weights)})
    '#' sig <- X %>% apply(1, function(x) {SDMTools:::wt.sd(x, weights)})
    mu <- rowMeans(X, weights = weights)
    sig <- rowSDs(X, weights = weights)
    '#' Added 12/9/19: save weighted scaling means and std devs
    vargenes_means_sds <- tibble(
        symbol = genes_use,
        mean = mu
    )
    vargenes_means_sds$stddev <- sig
    '#' finish added 12/9/19
    X <- scaleDataWithStats(X, mu, sig) 
    X <- X[which(is.na(rowSums(X)) == 0), ]
    if (do_corr) {
        X <- X %>% scale() %>% pmin(scale_thresh) %>% pmax(-scale_thresh)
    }
    '##' weighted SVD
    '#' pres <- rsvd::rsvd(X %*% Matrix::Diagonal(x = sqrt(weights)), k = npc)
    pres <- RSpectra::svds(X %*% Matrix::Diagonal(x = sqrt(weights)), npc)
    V <- (Matrix::Diagonal(x = 1 / sqrt(weights)) %*% pres$v) %*% diag(pres$d)
    V <- as.matrix(V)
    colnames(V) <- paste0('PC', 1:npc)
    row.names(V) <- colnames(X)
    colnames(pres$u) <- paste0('PC', 1:npc)
    row.names(pres$u) <- row.names(X)
    return(list(loadings = pres$u, embeddings = V, vargenes = vargenes_means_sds))
}

Any clarity on this topic would be greatly appreciated!

Cheers, Marc

**Comment by mhwadsworth91** [comment]
Hello Raychaudhuri Lab,

Gentle bump on this.

Cheers, Marc

**Comment by miltargid** [comment]
Hi,

Weights are calculated based on the number of cells in each data-set to be integrated.
They showcase it in the paper and the corresponding notebook is available here.

Check this out
https://github.com/immunogenomics/FibroblastAtlas2021/blob/main/Analyses_human/AllCells.ipynb
Hope it helps.
